<?php

namespace App\Models;

use App\Models\Traits\IsQueriable;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Author extends Model
{
    use HasFactory, IsQueriable;

    protected $searchBy = ['name', 'last_name'];

    public function books()
    {
        return $this->belongsToMany(Book::class);
    }

    public function __toString()
    {
        return "{$this->name} {$this->last_name}"; // TODO: Change the autogenerated stub
    }
}
