version: '3'
services:
    server:
        container_name: nginx-container
        build:
            context: .
            dockerfile: ./nginx/Dockerfile
        restart: always
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./nginx/library.conf:/etc/nginx/conf.d/library.conf
            - ./php/src:/var/www/html/
        links:
            - php:php
        ports:
            - "8000:80"
        tty: true
        networks:
            - library_network
    db:
        image: mysql:8.0
        container_name: db-container
        restart: unless-stopped
        tty: true
        environment:
            MYSQL_DATABASE: "library"
            MYSQL_USER: "library"
            MYSQL_PASSWORD: "1234"
            MYSQL_ROOT_PASSWORD: "toor"
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-p1234"]
            retries: 3
            timeout: 5s
        ports:
            - "3306:3306"
        networks:
            - library_network   
    php:
        container_name: php-container
        build:
            context: .
            dockerfile: php/Dockerfile
        
        depends_on:
            - db
        restart: unless-stopped
        tty: true
        volumes:
            - ./php/src:/var/www/html
        ports:
            - "9000:9000"
        links:
            - db:db
        networks:
            - library_network 
networks:
    library_network:
        driver: bridge
